spring:
  application:
    name: app-fire-gateway
  cloud:
    gateway:
      routes:
        - id: business-route
          uri: lb://app-fire-business
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
        - id: sys-route
          uri: lb://app-fire-sys
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/