spring:
  application:
    name: app-fair-security
  security:
    user:
      name: fire
      password: 1234
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
    appname: fair-security
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/